env:
 BUILDEVENTS_APIKEY: "hcamk_01k0q4h1t8fys0xvjw3vteb3v4"
 BUILDEVENTS_DATASET: "ci-buildkite"
 
steps:
  - label: ":microscope: Trace Test with buildevents"
    command: 
    # Send test span
      /Users/ivannalisetska/buildevents cmd "$BUILD_ID" "$STEP_ID" "sleep-span" -- sleep 2

      
