steps:
  - label: ":wave: Hello"
    key: "hello-step"
    commands:
      - echo "--- Starting trace"
      - export TRACE_ID=$(date +%s)
      - /Users/ivannalisetska/buildevents step $BUILDKITE_BUILD_ID
