env: 
BUILDKITE_TRACING_BACKEND: "opentelemetry"
BUILDKITE_TRACING_PROPAGATE_TRACEPARENT: "true"
OTEL_SERVICE_NAME: "buildkite-agent"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

steps:
  - label: ":microscope: Trace Test with buildevents"
    command: |
     export OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=c93bx72yva2ek6dgs8032qnq4zvrn3p3,x-honeycomb-dataset=ci-buildkite
    # Send test span
      /Users/ivannalisetska/buildevents cmd "$BUILD_ID" "$STEP_ID" "sleep-span" -- sleep 2

      
