env: 
 BUILDEVENTS_APIKEY: "c93bx72yva2ek6dgs8032qnq4zvrn3p3
# BUILDEVENTS_DATASET: "ci-buildkite"
 BUILDKITE_TRACING_BACKEND: "opentelemetry"
 BUILDKITE_TRACING_PROPAGATE_TRACEPARENT: "true"
 OTEL_SERVICE_NAME: "buildkite-agent"
 OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

steps:
  - label: ":microscope: Trace Test with buildevents"
    command: 
    # Send test span
      /Users/ivannalisetska/buildevents cmd "$BUILD_ID" "$STEP_ID" "sleep-span" -- sleep 2

      
