steps:
  - label: ":microscope: Trace Test"
    command:
      - echo "TRACEPARENT: $TRACEPARENT"
      - export TRACE_ID=$(echo $TRACEPARENT | cut -d'-' -f2)
      - export PARENT_SPAN_ID=$(echo $TRACEPARENT | cut -d'-' -f3)
      - export BUILD_ID="bk-$BUILDKITE_BUILD_ID"

      # Run a test span
      - /usr/local/bin/buildevents cmd "$BUILD_ID" "$TRACE_ID" "$PARENT_SPAN_ID" "sleep-span" -- sleep 2
