steps:
  - label: ":detective: Detect affected projects"
    key: "detect"
    command: |
      echo "web-app" > affected.txt

  - label: ":gear: Generate dynamic pipeline"
    depends_on: "detect"
    command: .buildkite/generate-dynamic.sh
