steps:
 - label: ":detective: Detect affected"
   key: "detect"
   command: |
    echo "web-app" > affected.txt
   artifact_paths:
    - affected.txt

 - label: ":gear: Generate dynamic pipeline"
   depends_on: "detect"
   command: |
    buildkite-agent artifact download affected.txt .
    sudo .buildkite/generate-pipeline.sh
