env:
      AFFECTED_PROJECTS: "web-app api"

steps:
  - label: ":detective: Detect changes"
    key: "detect"
    command: |
      export AFFECTED_PROJECTS="web-app api"
    

  - label: ":gear: Generate dynamic pipeline"
    depends_on: "detect"
    command: .buildkite/generate-pipeline.sh
    env:
      AFFECTED_PROJECTS: "${AFFECTED_PROJECTS}"
