env:
  BUILDEVENT_APIKEY: "kL18jQD3CEi4a4kbfofa9F"
  BUILDEVENT_DATASET: "buildkite"
  BUILDEVENT_CIPROVIDER: "Buildkite"

steps:
  - label: ":honeybee: Traced Span with Parent Context"
    commands:
      - echo "--- Extracting TRACEPARENT"
      - echo "TRACEPARENT: $TRACEPARENT"
      - export TRACE_ID=$(echo "$TRACEPARENT" | cut -d'-' -f2)
      - export PARENT_ID=$(echo "$TRACEPARENT" | cut -d'-' -f3)
      - export SPAN_NAME="child-npm-version"
      - export START_TIME=$(date +%s)
      - echo "--- Running child span with buildevents"
      - $BUILDEVENT_BIN cmd \
          --trace-id "$TRACE_ID" \
          --parent-id "$PARENT_ID" \
          "$BUILDKITE_BUILD_ID" "$BUILDKITE_JOB_ID" "$SPAN_NAME" -- \
          bash -c "npm --version"
      - echo "--- Finalizing span"
      - $BUILDEVENT_BIN step "$BUILDKITE_BUILD_ID" "$BUILDKITE_JOB_ID" "$START_TIME" "$SPAN_NAME"
