ENV: 
 BUILDKITE_TRACING_SERVICE_NAME: "buildkite"
 BUILDEVENTS_APIKEY: "c93bx72yva2ek6dgs8032qnq4zvrn3p3"
 BUILDEVENTS_DATASET: "buildevents"
 BUILDKITE_TRACING_BACKEND: "opentelemetry"
 BUILDKITE_TRACING_PROPAGATE_TRACEPARENT: "true"
 OTEL_SERVICE_NAME: "buildkite-agent"
 OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

steps:
  - label: ":link: Test Buildevents Child Span"
    command: |
      echo "TRACEPARENT: $TRACEPARENT"

      export TRACE_ID=$(echo "$TRACEPARENT" | cut -d'-' -f2)
      export PARENT_SPAN_ID=$(echo "$TRACEPARENT" | cut -d'-' -f3)

      echo "TRACE_ID: $TRACE_ID"
      echo "PARENT_SPAN_ID: $PARENT_SPAN_ID"

      /Users/ivannalisetska/buildevents cmd "$TRACE_ID" "$PARENT_SPAN_ID" "sleep-span" -- sleep 2
    env:
      BUILDEVENTS_API_KEY: "c93bx72yva2ek6dgs8032qnq4zvrn3p3"  # Optional if not pre-set
      BUILDEVENTS_DATASET: "buildevents"

      
