env:
  BUILDEVENT_APIKEY: "kL18jQD3CEi4a4kbfofa9F"
  BUILDEVENT_DATASET: "buildkite"
  BUILDEVENT_CIPROVIDER: "Buildkite"

steps:
  - label: ":honeybee: Traced npm version"
    command: >
      /Users/ivannalisetska/buildevents cmd "$BUILDKITE_BUILD_ID" "$BUILDKITE_JOB_ID" "npm-version" -- bash -c "npm --version";
      /Users/ivannalisetska/buildevents step "$BUILDKITE_BUILD_ID" "$BUILDKITE_JOB_ID" "$(date +%s)" "npm-version"
