steps:
  - label: ":microscope: Trace Test with buildevents"
    command: |
      echo "TRACEPARENT: $TRACEPARENT"

      export TRACE_ID=$(echo "$TRACEPARENT" | cut -d'-' -f2)
      export PARENT_SPAN_ID=$(echo "$TRACEPARENT" | cut -d'-' -f3)
      export BUILD_ID="bk-$BUILDKITE_BUILD_ID"
      export STEP_ID="${BUILDKITE_JOB_ID:-manual-step-id}"

      echo "BUILD_ID: $BUILD_ID"
      echo "STEP_ID: $STEP_ID"
      echo "TRACE_ID: $TRACE_ID"
      echo "PARENT_SPAN_ID: $PARENT_SPAN_ID"

      if [ -n "$BUILDEVENTS_APIKEY" ]; then
        echo "BUILDEVENTS_APIKEY is set"
      else
        echo "❌ BUILDEVENTS_APIKEY is NOT set"
      fi

      echo "BUILDEVENTS_DATASET: $BUILDEVENTS_DATASET"
      echo "BUILDEVENTS_ENDPOINT: ${BUILDEVENTS_ENDPOINT:-default}"

      # Send test span
      /usr/local/bin/buildevents cmd "$BUILD_ID" "$STEP_ID" "sleep-span" -- sleep 2
    env:
      BUILDEVENTS_APIKEY: "hcamk_01k0q4h1t8fys0xvjw3vteb3v4"
      BUILDEVENTS_DATASET: "buildevents"
