steps:
  - label: "Generate Diff - {{matrix.queue}}"
    key: "diff-job"
    matrix:
      setup:
        queue:
          - "75"
          - "86"
    command: |
      echo "Matrix value: $BUILDKITE_MATRIX_QUEUE"
      echo "Patch generated for queue $BUILDKITE_MATRIX_QUEUE" > "s3_engine_diff_${BUILDKITE_MATRIX_QUEUE}.patch"
      
      echo "--- Files before upload ---"
      ls -lh s3_engine_diff_*.patch
      
      buildkite-agent artifact upload "s3_engine_diff_${BUILDKITE_MATRIX_QUEUE}.patch"

  - label: ":mag: Download All Artifacts"
    depends_on: "diff-job"
    command: |
      echo "--- Downloading ---"
      buildkite-agent artifact download "s3_engine_diff_*.patch" .

      echo "--- Downloaded files ---"
      ls -lh s3_engine_diff_*.patch || echo "No patch files found"

      echo "--- File contents ---"
      cat s3_engine_diff_75.patch || echo "Missing s3_engine_diff_75.patch"
      cat s3_engine_diff_86.patch || echo "Missing s3_engine_diff_86.patch"
