steps:
  - label: ":bash: Decide pipelines to trigger"
    key: "decision-step"
    command: |
      echo "sandbox" > pipelines-to-trigger.txt

  - label: ":buildkite: Upload dynamic steps"
    depends_on: "decision-step"
    command: .buildkite/generate-pipeline.sh
