env:
  BUILDEVENT_APIKEY: "kL18jQD3CEi4a4kbfofa9F"
  BUILDEVENT_DATASET: "buildkite"
  BUILDEVENT_CIPROVIDER: "Buildkite"

steps:
  - label: ":mag: Echo TRACEPARENT"
    command:
      - echo "TRACEPARENT: $TRACING_PROPAGATE_TRACEPARENT"
