env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://bucket-A"

steps:
  - label: "Failing step"
    command: "echo test"
    concurrency: 1
    concurrency_group: "test-group"
    agents:
      queue: runners
