steps:
  - label: ":test-tube: Run Tests"
    command: "echo 'Running tests for my-test-pipeline'"
    
  - label: ":package: Build Package"
    command: "echo 'Building package for my-test-pipeline'"

